# Generated by Django 4.0.4 on 2022-05-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_reviews_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-time_create', 'name'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзыв'},
        ),
        migrations.AddField(
            model_name='movie',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time_movies',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='Продолжительность (мин)'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Отзыв на Фильм'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
    ]
