# Generated by Django 4.0.4 on 2022-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_reviews_options_movie_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлён'),
        ),
    ]
